### ISSUE TITLE
Configuration.json

### ISSUE THREAD

**Issue by BigMaccccc** [GitHub-TC/EmpyrionVotingRewardMod#2]
Hello,

I have a problem with the coding of the Configuration.json.

Indeed when I put : 
"StatsRewards": [
    {
      "Type": "Health",
      "AddCount": 1,
      "MaxCount": 800
    },
    {
      "Type": "Stamina",
      "AddCount": 1,
      "MaxCount": 800
    }
  ],

For example, it works during the game, but once the server restarts, it does not restart. I have to remove these lines to make it work again.

Do you have an idea?  

Translated with www.DeepL.com/Translator (free version)

**Comment by GitHub-TC** [comment]
I can hardly imagine that this hinders the server start. Please post the "Dedicated..." dogfile from a failed server start

**Comment by BigMaccccc** [comment]
I have solved the problem, but when we do a /voteforstat XXXX it does not count any votes. Is this normal? 

Here my Configuration.json is :
"StatsRewards": [
    {
      "Type": "Health",
      "AddCount": 5,
      "MaxCount": 800
    },
    {
      "Type": "Stamina",
      "AddCount": 5,
      "MaxCount": 800
    }

Thx a lot.

**Comment by GitHub-TC** [comment]
works on many other servers so this must be anothe reason
